`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 08.04.2025 21:18:37
// Design Name: 
// Module Name: tb_MLP_NN_HDL
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////


module tb_MLP_NN_HDL(

    );
    
    reg                          ACLK = 0;    // Synchronous clock
    reg                          ARESETN; // System reset, active low
    // slave in interface
    wire                         S_AXIS_TREADY;  // Ready to accept data in
    reg      [31 : 0]            S_AXIS_TDATA;   // Data in
    reg                          S_AXIS_TLAST;   // Optional data in qualifier
    reg                          S_AXIS_TVALID;  // Data in is valid
    // master out interface
    wire                         M_AXIS_TVALID;  // Data out is valid
    wire     [31 : 0]            M_AXIS_TDATA;   // Data out
    wire                         M_AXIS_TLAST;   // Optional data out qualifier
    reg                          M_AXIS_TREADY;  // Connected slave device is ready to accept data out
    
    myip_v1_1 U1 ( 
                .ACLK(ACLK),
                .ARESETN(ARESETN),
                .S_AXIS_TREADY(S_AXIS_TREADY),
                .S_AXIS_TDATA(S_AXIS_TDATA),
                .S_AXIS_TLAST(S_AXIS_TLAST),
                .S_AXIS_TVALID(S_AXIS_TVALID),
                .M_AXIS_TVALID(M_AXIS_TVALID),
                .M_AXIS_TDATA(M_AXIS_TDATA),
                .M_AXIS_TLAST(M_AXIS_TLAST),
                .M_AXIS_TREADY(M_AXIS_TREADY)
	);
	localparam NUMBER_OF_WEIGHTS  = 19 + 1;
	localparam NUMBER_OF_INPUT_WORDS  = 8;  // length of an input vector
	localparam NUMBER_OF_OUTPUT_WORDS  = 1;  // length of an output vector
	localparam NUMBER_OF_TEST_VECTORS  = 64;  // number of such test vectors (cases)
	localparam width  = 8;  // width of an input vector
           
	reg [width-1:0] test_input_memory [0:(NUMBER_OF_TEST_VECTORS*NUMBER_OF_INPUT_WORDS + NUMBER_OF_WEIGHTS)-1]; // 4 inputs * 2
	reg [width-1:0] test_result_expected_memory [0:NUMBER_OF_TEST_VECTORS*NUMBER_OF_OUTPUT_WORDS-1]; // 4 outputs *2
	reg [width-1:0] result_memory [0:NUMBER_OF_TEST_VECTORS*NUMBER_OF_OUTPUT_WORDS-1]; // same size as test_result_expected_memory
	
	integer word_cnt, input_cnt, output_cnt;
	reg success = 1'b1;
	reg M_AXIS_TLAST_prev = 1'b0;
	
	always@(posedge ACLK)
		M_AXIS_TLAST_prev <= M_AXIS_TLAST;
           
	always
		#50 ACLK = ~ACLK;
             
           initial
           begin
               	$display("Loading Memory.");
        		$readmemh("test_input_HDL_MLP_NN.mem", test_input_memory); // add the .mem file to the project or specify the complete path
        		$readmemh("test_result_expected_HDL_MLP_NN.mem", test_result_expected_memory); // add the .mem file to the project or specify the complete path
        		#1000						// to make inputs and capture from testbench not aligned with clock edges
               	ARESETN = 1'b0; 		// apply reset (active low)
               	S_AXIS_TVALID = 1'b0;   // no valid data placed on the S_AXIS_TDATA yet
               	S_AXIS_TLAST = 1'b0; 	// not required unless we are dealing with an unknown number of inputs. Ignored by the coprocessor. We will be asserting it correctly anyway
               	M_AXIS_TREADY = 1'b0;	// not ready to receive data from the co-processor yet.   

               	#100 					// hold reset for 100 ns.
               	ARESETN = 1'b1;			// release reset

               	
               	for(input_cnt=0; input_cnt < (NUMBER_OF_TEST_VECTORS*NUMBER_OF_INPUT_WORDS + NUMBER_OF_WEIGHTS);)
               	begin
               	//// Input 
					S_AXIS_TVALID = 1'b1;   // data is ready at the input of the coprocessor
					//while(!S_AXIS_TREADY)
					//begin
					//end
					
                    if(S_AXIS_TREADY)	// S_AXIS_TREADY is asserted by the coprocessor in response to S_AXIS_TVALID
                    begin
                        S_AXIS_TDATA = test_input_memory[input_cnt]; // set the next data ready
                        input_cnt=input_cnt+1;
                        if(input_cnt == (NUMBER_OF_TEST_VECTORS*NUMBER_OF_INPUT_WORDS + NUMBER_OF_WEIGHTS)-1)
                            S_AXIS_TLAST = 1'b1; 
                        else
                            S_AXIS_TLAST = 1'b0;
                    end
                    #100;			// wait for one clock cycle before for co-processor to capture data (if S_AXIS_TREADY was set
					S_AXIS_TLAST = 1'b0;
                end							// next test vector
                S_AXIS_TVALID = 1'b0;
				/// Output
				// Note: result_memory is not written at a clock edge, which is fine as it is just a testbench construct and not actual hardware
                for(output_cnt=0; output_cnt < NUMBER_OF_TEST_VECTORS*NUMBER_OF_OUTPUT_WORDS;)
                begin
                    M_AXIS_TREADY = 1'b1;	// we are now ready to receive data
                    if(M_AXIS_TLAST | ~M_AXIS_TLAST_prev) // receive data until the falling edge of M_AXIS_TLAST
                    begin
                        if(M_AXIS_TVALID)
                        begin
                            result_memory[output_cnt] = M_AXIS_TDATA;
                            output_cnt=output_cnt+1;
                        end
                        #100;
                    end						// receive loop
                    M_AXIS_TREADY = 1'b0;	// not ready to receive data from the co-processor anymore.				
				end
				
				// checking correctness of results
				for(word_cnt=0; word_cnt < NUMBER_OF_TEST_VECTORS*NUMBER_OF_OUTPUT_WORDS; word_cnt=word_cnt+1)
						success = success & (result_memory[word_cnt] == test_result_expected_memory[word_cnt]);
				if(success)
					$display("Test Passed.");
				else
					$display("Test Failed.");
               	
               $finish;       	
           end 

endmodule
